/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Всегда возвращает 200 OK пока процесс жив. Не проверяет внешние зависимости.
         */
        get: operations["get_api_health_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Проверяет доступность Postgres и Redis. Возвращает 503 при деградации зависимостей.
         */
        get: operations["get_api_health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaceanalytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать маркетплейс-аналитику
         * @description Создаёт новый объект marketplace analytics для активной компании. Компания определяется по сессии через ActiveCompanyService.
         */
        post: operations["post_api_marketplaceanalytics_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace-analytics/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список снэпшотов аналитики
         * @description Возвращает постраничный список снэпшотов маркетплейс-аналитики для активной компании с фильтрами по маркетплейсу, листингу и диапазону дат.
         */
        get: operations["get_marketplace_analytics_api_snapshot_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace-analytics/snapshots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Снэпшот по ID
         * @description Возвращает конкретный снэпшот аналитики. Проверяет принадлежность активной компании (multi-tenancy).
         */
        get: operations["get_marketplace_analytics_api_snapshot_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details.
         *     Целевой формат ошибок для нового API.
         *     Существующие эндпоинты могут возвращать legacy-форматы — см. описание конкретного ответа.
         */
        Problem: {
            /**
             * Format: uri
             * @description URI идентификатор типа ошибки
             * @example about:blank
             */
            type?: string;
            /**
             * @description Краткое человекочитаемое описание ошибки
             * @example Validation Failed
             */
            title: string;
            /**
             * @description HTTP status code
             * @example 422
             */
            status: number;
            /**
             * @description Детальное описание конкретного случая
             * @example Поле title обязательно
             */
            detail?: string;
            /**
             * @description URI запроса, в котором произошла ошибка
             * @example /api/marketplaceanalytics
             */
            instance?: string;
        };
        /** @description Тело запроса на создание маркетплейс-аналитики */
        CreateMarketplaceAnalyticsRequest: {
            /** @example Аналитика за Q1 2026 */
            title: string;
        };
        /** @description Разбивка себестоимости по статьям (decimal as string) */
        CostBreakdown: {
            /** @example 0.00 */
            other: string;
            /** @example 0.00 */
            storage: string;
            /** @example 0.00 */
            acquiring: string;
            /** @example 0.00 */
            penalties: string;
            /** @example 0.00 */
            acceptance: string;
            /** @example 0.00 */
            commission: string;
            /** @example 0.00 */
            logistics_to: string;
            /** @example 0.00 */
            logistics_back: string;
            /** @example 0.00 */
            advertising_cpc: string;
            /** @example 0.00 */
            advertising_other: string;
            /** @example 0.00 */
            advertising_external: string;
        };
        /** @description Метрики CPC-рекламы */
        AdvertisingCpcDetails: {
            /**
             * Format: float
             * @description Conversion rate
             * @example 0
             */
            cr: number;
            /** @example 0.00 */
            cpc: string;
            /** @example 0.00 */
            cpm: string;
            /** @example 0.00 */
            cpo: string;
            /**
             * Format: float
             * @example 0
             */
            ctr: number;
            /** @example 0.00 */
            acos: string;
            /** @example 0.00 */
            spend: string;
            /** @example 0 */
            clicks: number;
            /** @example 0 */
            orders: number;
            /** @example 0.00 */
            revenue: string;
            /** @example 0 */
            impressions: number;
        };
        /** @description Прочие рекламные расходы */
        AdvertisingOtherDetails: {
            /** @example 0.00 */
            spend: string;
            /** @description Детализация (структура элементов зависит от источника) */
            details: {
                [key: string]: unknown;
            }[];
        };
        /** @description Рекламные метрики (CPC + прочие расходы) */
        AdvertisingDetails: {
            cpc: components["schemas"]["AdvertisingCpcDetails"];
            other: components["schemas"]["AdvertisingOtherDetails"];
        };
        /** @description Снэпшот маркетплейс-аналитики по конкретному листингу за день */
        SnapshotResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            listing_id: string;
            /** @example Мышеловка. Крысоловка металлическая */
            listing_name: string;
            /** @example 3230225798 */
            listing_sku: string;
            /**
             * @description Код маркетплейса (значения enum MarketplaceType)
             * @example ozon
             * @enum {string}
             */
            marketplace: "wildberries" | "ozon" | "yandex_market" | "sber_megamarket";
            /**
             * Format: date
             * @example 2026-04-09
             */
            snapshot_date: string;
            /**
             * Format: date-time
             * @example 2026-04-10T08:11:55+03:00
             */
            calculated_at: string;
            /**
             * @description Выручка (decimal as string)
             * @example 0.00
             */
            revenue: string;
            /**
             * @description Возвраты (decimal as string)
             * @example 0.00
             */
            refunds: string;
            /**
             * @description Средняя цена продажи (decimal as string)
             * @example 0.00
             */
            avg_sale_price: string;
            /**
             * @description Себестоимость единицы; null если не указана
             * @example null
             */
            cost_price: string | null;
            /**
             * @description Общая себестоимость за период; null если не рассчитана
             * @example null
             */
            total_cost_price: string | null;
            /** @example 0 */
            orders_quantity: number;
            /** @example 0 */
            sales_quantity: number;
            /** @example 0 */
            delivered_quantity: number;
            /** @example 0 */
            returns_quantity: number;
            /**
             * @description Флаги проблем с качеством данных (значения enum DataQualityFlag)
             * @example [
             *       "cost_price_missing",
             *       "api_advertising_missing"
             *     ]
             */
            data_quality: ("cost_price_missing" | "api_advertising_missing" | "api_storage_missing" | "api_orders_missing" | "data_delayed")[];
            cost_breakdown: components["schemas"]["CostBreakdown"];
            advertising_details: components["schemas"]["AdvertisingDetails"];
        };
        /** @description Метаданные пагинации для list-эндпоинтов */
        PaginationMeta: {
            /**
             * @description Общее количество элементов
             * @example 7308
             */
            total: number;
            /**
             * @description Текущая страница (1-based)
             * @example 1
             */
            page: number;
            /**
             * @description Элементов на странице
             * @example 20
             */
            per_page: number;
            /**
             * @description Общее количество страниц
             * @example 366
             */
            pages: number;
        };
        /** @description Пагинированный список снэпшотов маркетплейс-аналитики */
        SnapshotListResponse: {
            data: components["schemas"]["SnapshotResponse"][];
            meta: components["schemas"]["PaginationMeta"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_health_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    get_api_health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все зависимости доступны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        checks?: {
                            /** @example true */
                            postgres?: boolean;
                            /** @example true */
                            redis_cache?: boolean;
                        };
                    };
                };
            };
            /** @description Одна или более зависимостей недоступны */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example fail */
                        status?: string;
                        checks?: {
                            /** @example false */
                            postgres?: boolean;
                            /** @example true */
                            redis_cache?: boolean;
                        };
                    };
                };
            };
        };
    };
    post_api_marketplaceanalytics_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMarketplaceAnalyticsRequest"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                    };
                };
            };
            /** @description Не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав (требуется ROLE_COMPANY_OWNER) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description У пользователя нет активной компании (ActiveCompanyService::getActiveCompany() бросает NotFoundHttpException) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка валидации входных данных (legacy-формат, не RFC 7807) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_marketplace_analytics_api_snapshot_index: {
        parameters: {
            query?: {
                /** @description Код маркетплейса (например, OZON, WB). Пустая строка трактуется как отсутствие фильтра. */
                marketplace?: string | null;
                /** @description Номер страницы, начиная с 1. */
                page?: number;
                /** @description Количество элементов на страницу. */
                perPage?: number;
                /** @description Начало периода в формате YYYY-MM-DD (включительно). */
                dateFrom?: string;
                /** @description Конец периода в формате YYYY-MM-DD (включительно). */
                dateTo?: string;
                /** @description UUID листинга для фильтрации. */
                listingId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Постраничный список снэпшотов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListResponse"];
                };
            };
            /** @description Неверный формат даты в dateFrom/dateTo (legacy-формат ошибки, не RFC 7807) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example BAD_REQUEST */
                        type?: string;
                        /** @example Неверный формат даты. Используйте YYYY-MM-DD. */
                        message?: string;
                    };
                };
            };
            /** @description Не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description У пользователя нет активной компании (ActiveCompanyService::getActiveCompany() бросает NotFoundHttpException) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_marketplace_analytics_api_snapshot_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID снэпшота */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Снэпшот найден */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Снэпшот не найден или не принадлежит активной компании (legacy-формат ошибки, не RFC 7807). Также возможен 404 без legacy-тела, если у пользователя нет активной компании (NotFoundHttpException из ActiveCompanyService). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example NOT_FOUND */
                        type?: string;
                        /** @example Снимок не найден */
                        message?: string;
                    };
                };
            };
        };
    };
}
