<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260329000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deals_deal_sequence DROP CONSTRAINT fk_deals_deal_sequence_company');
        $this->addSql('DROP TABLE product_import_sequences');
        $this->addSql('DROP TABLE deals_deal_sequence');
        $this->addSql('ALTER TABLE audit_log ALTER action TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE audit_log ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN audit_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE balance_categories ADD CONSTRAINT FK_6250404A979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_6250404A979B1AD6 ON balance_categories (company_id)');
        $this->addSql('ALTER TABLE balance_category_links ADD CONSTRAINT FK_D79DC3BA979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE balance_category_links ADD CONSTRAINT FK_D79DC3BA12469DE2 FOREIGN KEY (category_id) REFERENCES balance_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_D79DC3BA979B1AD6 ON balance_category_links (company_id)');
        $this->addSql('CREATE INDEX IDX_D79DC3BA12469DE2 ON balance_category_links (category_id)');
        $this->addSql('ALTER TABLE billing_feature ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE billing_integration ALTER billing_type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE billing_plan ALTER billing_period TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE billing_plan ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN billing_plan.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE billing_subscription ALTER status TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE billing_subscription ALTER trial_ends_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription ALTER current_period_start TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription ALTER current_period_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN billing_subscription.trial_ends_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN billing_subscription.current_period_start IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN billing_subscription.current_period_end IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN billing_subscription.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE billing_subscription ADD CONSTRAINT FK_16912F26979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_16912F26979B1AD6 ON billing_subscription (company_id)');
        $this->addSql('ALTER TABLE billing_subscription_integration ALTER status TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE billing_subscription_integration ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription_integration ALTER ended_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN billing_subscription_integration.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN billing_subscription_integration.ended_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE billing_usage_counter ALTER period_key TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE billing_usage_counter ADD CONSTRAINT FK_52C4B3BF979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_52C4B3BF979B1AD6 ON billing_usage_counter (company_id)');
        $this->addSql('ALTER TABLE bot_links ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN bot_links.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE cash_file_import_jobs ALTER options DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_cash_file_import_jobs_import_log RENAME TO IDX_3F785CF79656E79E');
        $this->addSql('ALTER TABLE cash_file_import_profile DROP CONSTRAINT fk_cash_file_import_profile_company');
        $this->addSql('ALTER TABLE cash_file_import_profile ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cash_file_import_profile ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cash_file_import_profile.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cash_file_import_profile.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE cash_file_import_profile ADD CONSTRAINT FK_573DA724979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX idx_cash_transaction_company_deleted_at');
        $this->addSql('ALTER TABLE cashflow_categories ALTER flow_kind DROP DEFAULT');
        $this->addSql('ALTER TABLE company_invites DROP CONSTRAINT fk_company_invites_accepted_by');
        $this->addSql('ALTER TABLE company_invites ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_invites ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_invites ALTER accepted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_invites ALTER revoked_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN company_invites.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_invites.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_invites.accepted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_invites.revoked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE company_invites ADD CONSTRAINT FK_232C70BB110B274A FOREIGN KEY (accepted_by_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_company_invites_token_hash RENAME TO UNIQ_232C70BBB3BC57DA');
        $this->addSql('ALTER TABLE company_members ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN company_members.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE deal_adjustments ALTER recognized_at TYPE DATE');
        $this->addSql('COMMENT ON COLUMN deal_adjustments.recognized_at IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE deal_charge_types ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE deal_charge_types ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN deal_charge_types.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN deal_charge_types.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE deal_charges ALTER recognized_at TYPE DATE');
        $this->addSql('COMMENT ON COLUMN deal_charges.recognized_at IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE documents ALTER source TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE documents ALTER stream TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE marketplace_barcode_catalog ALTER marketplace TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE marketplace_cost_categories ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_cost_categories ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_cost_categories ALTER deleted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_cost_categories.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_cost_categories.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_cost_categories.deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE marketplace_cost_pl_mappings ALTER include_in_pl DROP DEFAULT');
        $this->addSql('ALTER TABLE marketplace_cost_pl_mappings ALTER is_negative DROP DEFAULT');
        $this->addSql('ALTER TABLE marketplace_cost_pl_mappings ALTER sort_order DROP DEFAULT');
        $this->addSql('ALTER TABLE marketplace_costs DROP CONSTRAINT fk_cost_raw_document');
        $this->addSql('DROP INDEX idx_cost_raw_document');
        $this->addSql('ALTER TABLE marketplace_costs ALTER cost_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_costs ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_costs ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_costs.cost_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_costs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_costs.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_cost_document RENAME TO IDX_BDEE8EFC33F7837');
        $this->addSql('DROP INDEX idx_inv_cost_company_listing_from');
        $this->addSql('DROP INDEX idx_inv_cost_company_listing_to');
        $this->addSql('ALTER TABLE marketplace_job_logs ALTER job_type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE marketplace_job_logs ALTER status TYPE VARCHAR(255)');
        $this->addSql('DROP INDEX uniq_company_marketplace_product');
        $this->addSql('ALTER TABLE marketplace_listings ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_listings ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_listings ALTER size DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN marketplace_listings.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_listings.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX idx_month_close_lookup');
        $this->addSql('ALTER TABLE marketplace_month_closes ADD settings JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER marketplace TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_sales_returns_status DROP DEFAULT');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_sales_returns_status TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_costs_status DROP DEFAULT');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_costs_status TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE marketplace_processing_batch ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_processing_batch ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_processing_batch ALTER completed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_processing_batch.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_processing_batch.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_processing_batch.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE marketplace_raw_documents ALTER period_from TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_raw_documents ALTER period_to TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_raw_documents ALTER synced_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_raw_documents.period_from IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_raw_documents.period_to IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_raw_documents.synced_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE marketplace_reconciliation_log ALTER checked_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_reconciliation_log.checked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE marketplace_returns ALTER return_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_returns ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_returns ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_returns.return_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_returns.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_returns.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_marketplace_returns_listing RENAME TO IDX_6FF09FB9D4619D1A');
        $this->addSql('ALTER INDEX idx_return_document RENAME TO IDX_6FF09FB9C33F7837');
        $this->addSql('ALTER TABLE marketplace_sale_mappings ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_sale_mappings ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_sale_mappings.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_sale_mappings.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_mapping_project_direction RENAME TO IDX_EFE00E4285D43DF4');
        $this->addSql('DROP INDEX idx_marketplace_order');
        $this->addSql('ALTER TABLE marketplace_sales ALTER sale_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_sales ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_sales ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_sales.sale_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_sales.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_sales.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE marketplace_staging ALTER record_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_staging ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_staging ALTER processed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_staging.record_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_staging.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN marketplace_staging.processed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_staging_listing RENAME TO IDX_59B45A39D4619D1A');
        $this->addSql('ALTER TABLE money_account ALTER minimum_safe_balance DROP DEFAULT');
        $this->addSql('DROP INDEX idx_moysklad_connections_company_name');
        $this->addSql('ALTER TABLE pl_categories ALTER expense_type TYPE VARCHAR(255)');
        $this->addSql('DROP INDEX uniq_product_barcode_company');
        $this->addSql('ALTER INDEX idx_product_barcodes_product RENAME TO IDX_74F8CFF34584665A');
        $this->addSql('DROP INDEX idx_product_imports_company');
        $this->addSql('DROP INDEX idx_product_imports_status');
        $this->addSql('DROP INDEX idx_purchase_price_company_product_from');
        $this->addSql('DROP INDEX idx_purchase_price_company_product_to');
        $this->addSql('ALTER TABLE product_purchase_prices ALTER effective_from TYPE DATE');
        $this->addSql('ALTER TABLE product_purchase_prices ALTER effective_to TYPE DATE');
        $this->addSql('ALTER TABLE product_purchase_prices ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN product_purchase_prices.effective_from IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN product_purchase_prices.effective_to IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN product_purchase_prices.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX uniq_company_internal_article');
        $this->addSql('DROP INDEX uniq_company_sku');
        $this->addSql('ALTER TABLE products ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE products ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN products.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN products.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE project_directions DROP CONSTRAINT fk_project_directions_parent');
        $this->addSql('ALTER TABLE project_directions ALTER sort DROP DEFAULT');
        $this->addSql('ALTER TABLE project_directions ADD CONSTRAINT FK_51FE1CDE727ACA70 FOREIGN KEY (parent_id) REFERENCES project_directions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_project_directions_parent RENAME TO IDX_51FE1CDE727ACA70');
        $this->addSql('ALTER TABLE telegram_bots ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN telegram_bots.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE product_import_sequences (company_id UUID NOT NULL, year SMALLINT NOT NULL, last_seq INT DEFAULT 0 NOT NULL, PRIMARY KEY(company_id, year))');
        $this->addSql('CREATE TABLE deals_deal_sequence (company_id UUID NOT NULL, last_number INT NOT NULL, PRIMARY KEY(company_id))');
        $this->addSql('ALTER TABLE deals_deal_sequence ADD CONSTRAINT fk_deals_deal_sequence_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marketplace_reconciliation_log ALTER checked_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_reconciliation_log.checked_at IS NULL');
        $this->addSql('ALTER TABLE "cash_file_import_jobs" ALTER options SET DEFAULT \'[]\'');
        $this->addSql('ALTER INDEX idx_3f785cf79656e79e RENAME TO idx_cash_file_import_jobs_import_log');
        $this->addSql('ALTER TABLE billing_subscription_integration ALTER status TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE billing_subscription_integration ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription_integration ALTER ended_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN billing_subscription_integration.started_at IS NULL');
        $this->addSql('COMMENT ON COLUMN billing_subscription_integration.ended_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_returns ALTER return_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_returns ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_returns ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_returns.return_date IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_returns.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_returns.updated_at IS NULL');
        $this->addSql('ALTER INDEX idx_6ff09fb9d4619d1a RENAME TO idx_marketplace_returns_listing');
        $this->addSql('ALTER INDEX idx_6ff09fb9c33f7837 RENAME TO idx_return_document');
        $this->addSql('ALTER TABLE billing_subscription DROP CONSTRAINT FK_16912F26979B1AD6');
        $this->addSql('DROP INDEX IDX_16912F26979B1AD6');
        $this->addSql('ALTER TABLE billing_subscription ALTER status TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE billing_subscription ALTER trial_ends_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription ALTER current_period_start TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription ALTER current_period_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE billing_subscription ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN billing_subscription.trial_ends_at IS NULL');
        $this->addSql('COMMENT ON COLUMN billing_subscription.current_period_start IS NULL');
        $this->addSql('COMMENT ON COLUMN billing_subscription.current_period_end IS NULL');
        $this->addSql('COMMENT ON COLUMN billing_subscription.created_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_month_closes DROP settings');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER marketplace TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_sales_returns_status SET DEFAULT \'pending\'');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_sales_returns_status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_costs_status SET DEFAULT \'pending\'');
        $this->addSql('ALTER TABLE marketplace_month_closes ALTER stage_costs_status TYPE VARCHAR(20)');
        $this->addSql('CREATE INDEX idx_month_close_lookup ON marketplace_month_closes (company_id, marketplace, year, month)');
        $this->addSql('ALTER TABLE marketplace_job_logs ALTER job_type TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE marketplace_job_logs ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE marketplace_staging ALTER record_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_staging ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_staging ALTER processed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_staging.record_date IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_staging.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_staging.processed_at IS NULL');
        $this->addSql('ALTER INDEX idx_59b45a39d4619d1a RENAME TO idx_staging_listing');
        $this->addSql('CREATE INDEX idx_moysklad_connections_company_name ON moysklad_connections (company_id, name)');
        $this->addSql('ALTER TABLE "telegram_bots" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "telegram_bots".updated_at IS NULL');
        $this->addSql('CREATE INDEX idx_inv_cost_company_listing_from ON marketplace_inventory_cost_prices (company_id, listing_id, effective_from)');
        $this->addSql('CREATE INDEX idx_inv_cost_company_listing_to ON marketplace_inventory_cost_prices (company_id, listing_id, effective_to)');
        $this->addSql('ALTER TABLE balance_category_links DROP CONSTRAINT FK_D79DC3BA979B1AD6');
        $this->addSql('ALTER TABLE balance_category_links DROP CONSTRAINT FK_D79DC3BA12469DE2');
        $this->addSql('DROP INDEX IDX_D79DC3BA979B1AD6');
        $this->addSql('DROP INDEX IDX_D79DC3BA12469DE2');
        $this->addSql('ALTER TABLE balance_categories DROP CONSTRAINT FK_6250404A979B1AD6');
        $this->addSql('DROP INDEX IDX_6250404A979B1AD6');
        $this->addSql('ALTER TABLE product_purchase_prices ALTER effective_from TYPE DATE');
        $this->addSql('ALTER TABLE product_purchase_prices ALTER effective_to TYPE DATE');
        $this->addSql('ALTER TABLE product_purchase_prices ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN product_purchase_prices.effective_from IS NULL');
        $this->addSql('COMMENT ON COLUMN product_purchase_prices.effective_to IS NULL');
        $this->addSql('COMMENT ON COLUMN product_purchase_prices.created_at IS NULL');
        $this->addSql('CREATE INDEX idx_purchase_price_company_product_from ON product_purchase_prices (company_id, product_id, effective_from)');
        $this->addSql('CREATE INDEX idx_purchase_price_company_product_to ON product_purchase_prices (company_id, product_id, effective_to)');
        $this->addSql('ALTER TABLE documents ALTER source TYPE VARCHAR(32)');
        $this->addSql('ALTER TABLE documents ALTER stream TYPE VARCHAR(32)');
        $this->addSql('ALTER TABLE cash_file_import_profile DROP CONSTRAINT FK_573DA724979B1AD6');
        $this->addSql('ALTER TABLE cash_file_import_profile ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cash_file_import_profile ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cash_file_import_profile.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN cash_file_import_profile.updated_at IS NULL');
        $this->addSql('ALTER TABLE cash_file_import_profile ADD CONSTRAINT fk_cash_file_import_profile_company FOREIGN KEY (company_id) REFERENCES companies (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_directions DROP CONSTRAINT FK_51FE1CDE727ACA70');
        $this->addSql('ALTER TABLE project_directions ALTER sort SET DEFAULT 0');
        $this->addSql('ALTER TABLE project_directions ADD CONSTRAINT fk_project_directions_parent FOREIGN KEY (parent_id) REFERENCES project_directions (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_51fe1cde727aca70 RENAME TO idx_project_directions_parent');
        $this->addSql('ALTER TABLE marketplace_listings ALTER size SET DEFAULT \'UNKNOWN\'');
        $this->addSql('ALTER TABLE marketplace_listings ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_listings ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_listings.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_listings.updated_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_company_marketplace_product ON marketplace_listings (company_id, marketplace, product_id) WHERE (product_id IS NOT NULL)');
        $this->addSql('ALTER TABLE deal_charge_types ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE deal_charge_types ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN deal_charge_types.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN deal_charge_types.updated_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_sales ALTER sale_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_sales ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_sales ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_sales.sale_date IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_sales.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_sales.updated_at IS NULL');
        $this->addSql('CREATE INDEX idx_marketplace_order ON marketplace_sales (marketplace, external_order_id)');
        $this->addSql('ALTER TABLE billing_plan ALTER billing_period TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE billing_plan ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN billing_plan.created_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_barcode_company ON product_barcodes (company_id, barcode)');
        $this->addSql('ALTER INDEX idx_74f8cff34584665a RENAME TO idx_product_barcodes_product');
        $this->addSql('ALTER TABLE deal_charges ALTER recognized_at TYPE DATE');
        $this->addSql('COMMENT ON COLUMN deal_charges.recognized_at IS NULL');
        $this->addSql('ALTER TABLE billing_feature ALTER type TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE billing_integration ALTER billing_type TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE marketplace_cost_pl_mappings ALTER include_in_pl SET DEFAULT true');
        $this->addSql('ALTER TABLE marketplace_cost_pl_mappings ALTER is_negative SET DEFAULT true');
        $this->addSql('ALTER TABLE marketplace_cost_pl_mappings ALTER sort_order SET DEFAULT 0');
        $this->addSql('ALTER TABLE billing_usage_counter DROP CONSTRAINT FK_52C4B3BF979B1AD6');
        $this->addSql('DROP INDEX IDX_52C4B3BF979B1AD6');
        $this->addSql('ALTER TABLE billing_usage_counter ALTER period_key TYPE VARCHAR(7)');
        $this->addSql('CREATE INDEX idx_product_imports_company ON product_imports (company_id)');
        $this->addSql('CREATE INDEX idx_product_imports_status ON product_imports (status)');
        $this->addSql('ALTER TABLE "cashflow_categories" ALTER flow_kind SET DEFAULT \'OPERATING\'');
        $this->addSql('ALTER TABLE "products" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "products" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "products".created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "products".updated_at IS NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_company_internal_article ON "products" (company_id, internal_article)');
        $this->addSql('CREATE UNIQUE INDEX uniq_company_sku ON "products" (company_id, sku)');
        $this->addSql('ALTER TABLE pl_categories ALTER expense_type TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE company_invites DROP CONSTRAINT FK_232C70BB110B274A');
        $this->addSql('ALTER TABLE company_invites ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_invites ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_invites ALTER accepted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_invites ALTER revoked_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN company_invites.expires_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_invites.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_invites.accepted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_invites.revoked_at IS NULL');
        $this->addSql('ALTER TABLE company_invites ADD CONSTRAINT fk_company_invites_accepted_by FOREIGN KEY (accepted_by_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_232c70bbb3bc57da RENAME TO uniq_company_invites_token_hash');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('ALTER TABLE "money_account" ALTER minimum_safe_balance SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE marketplace_costs ALTER cost_date TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_costs ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_costs ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_costs.cost_date IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_costs.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_costs.updated_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_costs ADD CONSTRAINT fk_cost_raw_document FOREIGN KEY (raw_document_id) REFERENCES marketplace_raw_documents (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_cost_raw_document ON marketplace_costs (raw_document_id)');
        $this->addSql('ALTER INDEX idx_bdee8efc33f7837 RENAME TO idx_cost_document');
        $this->addSql('ALTER TABLE "bot_links" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "bot_links".updated_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_barcode_catalog ALTER marketplace TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE company_members ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN company_members.created_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_cost_categories ALTER deleted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_cost_categories ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_cost_categories ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_cost_categories.deleted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_cost_categories.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_cost_categories.updated_at IS NULL');
        $this->addSql('CREATE INDEX idx_cash_transaction_company_deleted_at ON cash_transaction (company_id, deleted_at)');
        $this->addSql('ALTER TABLE marketplace_sale_mappings ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_sale_mappings ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_sale_mappings.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_sale_mappings.updated_at IS NULL');
        $this->addSql('ALTER INDEX idx_efe00e4285d43df4 RENAME TO idx_mapping_project_direction');
        $this->addSql('ALTER TABLE audit_log ALTER action TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE audit_log ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN audit_log.created_at IS NULL');
        $this->addSql('ALTER TABLE deal_adjustments ALTER recognized_at TYPE DATE');
        $this->addSql('COMMENT ON COLUMN deal_adjustments.recognized_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_processing_batch ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_processing_batch ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE marketplace_processing_batch ALTER completed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_processing_batch.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_processing_batch.started_at IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_processing_batch.completed_at IS NULL');
        $this->addSql('ALTER TABLE marketplace_raw_documents ALTER period_from TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_raw_documents ALTER period_to TYPE DATE');
        $this->addSql('ALTER TABLE marketplace_raw_documents ALTER synced_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN marketplace_raw_documents.period_from IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_raw_documents.period_to IS NULL');
        $this->addSql('COMMENT ON COLUMN marketplace_raw_documents.synced_at IS NULL');
    }
}
