<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Removes the retired Ingestion -> P&L projection and its generated aggregates.
 *
 * Categorized rows generated by that projection are identified by rebuilt_at.
 * Uncategorized rows can contain both legacy and projected amounts, so they are
 * retained and reported for manual reconciliation. The migration is intentionally
 * data-destructive; down() restores only the former schema.
 */
final class Version20260806120000 extends AbstractMigration
{
    public function isTransactional(): bool
    {
        return true;
    }

    public function getDescription(): string
    {
        return 'Remove Ingestion P&L projection data, dirty periods, and rebuild audit columns';
    }

    public function up(Schema $schema): void
    {
        $this->abortUnlessPostgreSql();

        $this->assertExpectedSchema($schema);

        $dailyRows = (int) $this->connection->fetchOne(
            'SELECT COUNT(*) FROM pl_daily_totals WHERE rebuilt_at IS NOT NULL AND pl_category_id IS NOT NULL',
        );
        $preservedDailyRows = (int) $this->connection->fetchOne(
            'SELECT COUNT(*) FROM pl_daily_totals WHERE rebuilt_at IS NOT NULL AND pl_category_id IS NULL',
        );
        $monthlyRows = (int) $this->connection->fetchOne(
            <<<'SQL'
                SELECT COUNT(*)
                FROM pl_monthly_snapshots snapshot
                WHERE (snapshot.rebuilt_at IS NOT NULL AND snapshot.pl_category_id IS NOT NULL)
                   OR EXISTS (
                       SELECT 1
                       FROM pl_daily_totals daily
                       WHERE daily.rebuilt_at IS NOT NULL
                         AND daily.pl_category_id IS NOT NULL
                         AND daily.company_id = snapshot.company_id
                         AND daily.pl_category_id = snapshot.pl_category_id
                         AND TO_CHAR(daily.date, 'YYYY-MM') = snapshot.period
                   )
                SQL,
        );
        $preservedMonthlyRows = (int) $this->connection->fetchOne(
            'SELECT COUNT(*) FROM pl_monthly_snapshots WHERE rebuilt_at IS NOT NULL AND pl_category_id IS NULL',
        );
        $dirtyPeriods = (int) $this->connection->fetchOne('SELECT COUNT(*) FROM pnl_dirty_periods');

        $this->write(sprintf(
            'Removing Ingestion P&L projection: %d categorized daily total(s), %d affected monthly snapshot(s), %d dirty period(s).',
            $dailyRows,
            $monthlyRows,
            $dirtyPeriods,
        ));
        $this->write(sprintf(
            'Preserving for manual reconciliation because they may contain legacy money: %d uncategorized daily total(s), %d uncategorized monthly snapshot(s).',
            $preservedDailyRows,
            $preservedMonthlyRows,
        ));

        $this->addSql(
            <<<'SQL'
                CREATE TEMPORARY TABLE ingestion_pnl_removed_periods ON COMMIT DROP AS
                SELECT DISTINCT company_id, pl_category_id, TO_CHAR(date, 'YYYY-MM') AS period
                FROM pl_daily_totals
                WHERE rebuilt_at IS NOT NULL
                  AND pl_category_id IS NOT NULL
                SQL,
        );
        $this->addSql('DELETE FROM pl_daily_totals WHERE rebuilt_at IS NOT NULL AND pl_category_id IS NOT NULL');
        $this->addSql(
            <<<'SQL'
                DELETE FROM pl_monthly_snapshots snapshot
                WHERE (snapshot.rebuilt_at IS NOT NULL AND snapshot.pl_category_id IS NOT NULL)
                   OR EXISTS (
                       SELECT 1
                       FROM ingestion_pnl_removed_periods affected
                       WHERE affected.company_id = snapshot.company_id
                         AND affected.pl_category_id = snapshot.pl_category_id
                         AND affected.period = snapshot.period
                   )
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                INSERT INTO pl_monthly_snapshots (
                    id,
                    company_id,
                    pl_category_id,
                    period,
                    amount_income,
                    amount_expense,
                    updated_at
                )
                SELECT gen_random_uuid(),
                       daily.company_id,
                       daily.pl_category_id,
                       affected.period,
                       SUM(daily.amount_income),
                       SUM(daily.amount_expense),
                       CURRENT_TIMESTAMP
                FROM ingestion_pnl_removed_periods affected
                INNER JOIN pl_daily_totals daily
                    ON daily.company_id = affected.company_id
                   AND daily.pl_category_id = affected.pl_category_id
                   AND TO_CHAR(daily.date, 'YYYY-MM') = affected.period
                GROUP BY daily.company_id, daily.pl_category_id, affected.period
                SQL,
        );
        $this->addSql('DROP TABLE ingestion_pnl_removed_periods');
        $this->addSql('DROP TABLE pnl_dirty_periods');
        $this->addSql('ALTER TABLE pl_daily_totals DROP COLUMN rebuilt_at');
        $this->addSql('ALTER TABLE pl_monthly_snapshots DROP COLUMN rebuilt_at');
    }

    public function down(Schema $schema): void
    {
        $this->abortUnlessPostgreSql();

        $this->warnIf(true, 'Deleted P&L projection rows and dirty-period history cannot be restored by down().');

        $this->addSql('ALTER TABLE pl_daily_totals ADD rebuilt_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE pl_monthly_snapshots ADD rebuilt_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql("CREATE TABLE pnl_dirty_periods (id UUID NOT NULL, company_id UUID NOT NULL, period_year SMALLINT NOT NULL, period_month SMALLINT NOT NULL, shop_ref VARCHAR(255) DEFAULT '' NOT NULL, status VARCHAR(32) DEFAULT 'pending' NOT NULL, reason VARCHAR(32) NOT NULL, marked_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, rebuilt_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL, attempts INT DEFAULT 0 NOT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_pdp_key ON pnl_dirty_periods (company_id, period_year, period_month, shop_ref)');
        $this->addSql('CREATE INDEX idx_pdp_status_marked ON pnl_dirty_periods (status, marked_at)');
        $this->addSql('CREATE INDEX idx_pdp_company_status ON pnl_dirty_periods (company_id, status)');
    }

    private function abortUnlessPostgreSql(): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->abortIf(
            !$platform instanceof PostgreSQLPlatform,
            sprintf('Migration %s supports only PostgreSQL; got platform "%s".', self::class, $platform::class),
        );
    }

    private function assertExpectedSchema(Schema $schema): void
    {
        foreach (['pl_daily_totals', 'pl_monthly_snapshots', 'pnl_dirty_periods'] as $tableName) {
            $this->abortIf(!$schema->hasTable($tableName), sprintf('Required table "%s" does not exist.', $tableName));
        }

        foreach (['pl_daily_totals', 'pl_monthly_snapshots'] as $tableName) {
            $this->abortIf(
                !$schema->getTable($tableName)->hasColumn('rebuilt_at'),
                sprintf('Required column "%s.rebuilt_at" does not exist.', $tableName),
            );
        }
    }
}
