<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251105174115 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wildberries_report_details (id UUID NOT NULL, company_id UUID NOT NULL, realizationreport_id BIGINT DEFAULT NULL, rrd_id BIGINT NOT NULL, sale_dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rr_dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, order_dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, nm_id BIGINT DEFAULT NULL, barcode VARCHAR(255) DEFAULT NULL, subject_name VARCHAR(255) DEFAULT NULL, brand_name VARCHAR(255) DEFAULT NULL, retail_price NUMERIC(15, 2) DEFAULT NULL, retail_price_with_disc_rub NUMERIC(15, 2) DEFAULT NULL, ppvz_sales_commission NUMERIC(15, 2) DEFAULT NULL, ppvz_for_pay NUMERIC(15, 2) DEFAULT NULL, delivery_rub NUMERIC(15, 2) DEFAULT NULL, storage_fee NUMERIC(15, 2) DEFAULT NULL, acceptance NUMERIC(15, 2) DEFAULT NULL, penalty NUMERIC(15, 2) DEFAULT NULL, acquiring_fee NUMERIC(15, 2) DEFAULT NULL, site_country VARCHAR(255) DEFAULT NULL, supplier_oper_name VARCHAR(255) DEFAULT NULL, doc_type_name VARCHAR(255) DEFAULT NULL, status_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C46D4BA979B1AD6 ON wildberries_report_details (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_company_rrd ON wildberries_report_details (company_id, rrd_id)');
        $this->addSql('COMMENT ON COLUMN wildberries_report_details.sale_dt IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wildberries_report_details.rr_dt IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wildberries_report_details.order_dt IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wildberries_report_details.status_updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wildberries_report_details.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wildberries_report_details.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE wildberries_report_details ADD CONSTRAINT FK_8C46D4BA979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auto_category_template DROP CONSTRAINT fk_ac_template_category');
        $this->addSql('ALTER TABLE auto_category_template DROP CONSTRAINT fk_ac_template_company');
        $this->addSql('ALTER TABLE auto_category_condition DROP CONSTRAINT fk_ac_condition_template');
        $this->addSql('DROP TABLE auto_category_template');
        $this->addSql('DROP TABLE auto_category_condition');
        $this->addSql('ALTER TABLE cash_transaction ALTER occurred_at TYPE DATE');
        $this->addSql('ALTER TABLE cash_transaction ALTER booked_at TYPE DATE');
        $this->addSql('ALTER TABLE cash_transaction ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cash_transaction.occurred_at IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cash_transaction.booked_at IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cash_transaction.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE cash_transaction ADD CONSTRAINT FK_925602C6979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cash_transaction ADD CONSTRAINT FK_925602C6B4D8145A FOREIGN KEY (money_account_id) REFERENCES "money_account" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cash_transaction ADD CONSTRAINT FK_925602C6DB1FAD05 FOREIGN KEY (counterparty_id) REFERENCES "counterparty" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cash_transaction ADD CONSTRAINT FK_925602C6C2F6CD90 FOREIGN KEY (cashflow_category_id) REFERENCES "cashflow_categories" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_925602C6979B1AD6 ON cash_transaction (company_id)');
        $this->addSql('CREATE INDEX IDX_925602C6B4D8145A ON cash_transaction (money_account_id)');
        $this->addSql('CREATE INDEX IDX_925602C6DB1FAD05 ON cash_transaction (counterparty_id)');
        $this->addSql('CREATE INDEX IDX_925602C6C2F6CD90 ON cash_transaction (cashflow_category_id)');
        $this->addSql('ALTER INDEX idx_ct_project_direction RENAME TO IDX_925602C685D43DF4');
        $this->addSql('ALTER INDEX idx_ctar_project_direction RENAME TO IDX_882E16E985D43DF4');
        $this->addSql('ALTER TABLE cashflow_categories DROP CONSTRAINT fk_cfc_parent');
        $this->addSql('ALTER TABLE cashflow_categories ALTER operation_type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE cashflow_categories ADD CONSTRAINT FK_EAB5C38D727ACA70 FOREIGN KEY (parent_id) REFERENCES "cashflow_categories" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_cfc_parent RENAME TO IDX_EAB5C38D727ACA70');
        $this->addSql('ALTER INDEX idx_cfc_company RENAME TO IDX_EAB5C38D979B1AD6');
        $this->addSql('ALTER TABLE companies ALTER finance_lock_before TYPE DATE');
        $this->addSql('COMMENT ON COLUMN companies.finance_lock_before IS \'(DC2Type:date_immutable)\'');
        $this->addSql('DROP INDEX idx_counterparty_company_name');
        $this->addSql('DROP INDEX uniq_counterparty_company_inn');
        $this->addSql('ALTER TABLE counterparty ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE counterparty ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN counterparty.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE document_operations DROP CONSTRAINT fk_doc_oper_document');
        $this->addSql('ALTER TABLE document_operations ADD CONSTRAINT FK_89D7F81EC33F7837 FOREIGN KEY (document_id) REFERENCES documents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_doc_oper_document RENAME TO IDX_89D7F81EC33F7837');
        $this->addSql('ALTER INDEX idx_doc_oper_category RENAME TO IDX_89D7F81E12469DE2');
        $this->addSql('ALTER INDEX idx_doc_oper_counterparty RENAME TO IDX_89D7F81EDB1FAD05');
        $this->addSql('DROP INDEX idx_documents_company_type_date');
        $this->addSql('ALTER TABLE documents ALTER date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN documents.date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_document_company RENAME TO IDX_A2B07288979B1AD6');
        $this->addSql('ALTER INDEX idx_document_counterparty RENAME TO IDX_A2B07288DB1FAD05');
        $this->addSql('ALTER TABLE import_log ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE import_log ALTER finished_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE import_log ALTER created_count DROP DEFAULT');
        $this->addSql('ALTER TABLE import_log ALTER skipped_duplicates DROP DEFAULT');
        $this->addSql('ALTER TABLE import_log ALTER errors_count DROP DEFAULT');
        $this->addSql('ALTER TABLE import_log ALTER preview DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN import_log.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN import_log.finished_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE money_account ALTER currency TYPE VARCHAR(3)');
        $this->addSql('ALTER TABLE money_account_daily_balance ALTER date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN money_account_daily_balance.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE money_account_daily_balance ADD CONSTRAINT FK_FCE321EB979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE money_account_daily_balance ADD CONSTRAINT FK_FCE321EBB4D8145A FOREIGN KEY (money_account_id) REFERENCES "money_account" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_FCE321EB979B1AD6 ON money_account_daily_balance (company_id)');
        $this->addSql('CREATE INDEX IDX_FCE321EBB4D8145A ON money_account_daily_balance (money_account_id)');
        $this->addSql('ALTER TABLE money_fund ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN money_fund.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE money_fund_movement ALTER occurred_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN money_fund_movement.occurred_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE ozon_order_items ADD CONSTRAINT FK_53F702428D9F6D38 FOREIGN KEY (order_id) REFERENCES ozon_orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ozon_order_items ADD CONSTRAINT FK_53F702424584665A FOREIGN KEY (product_id) REFERENCES "ozon_products" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_53F702428D9F6D38 ON ozon_order_items (order_id)');
        $this->addSql('ALTER TABLE ozon_order_status_history ALTER changed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN ozon_order_status_history.changed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE ozon_order_status_history ADD CONSTRAINT FK_EF53A0928D9F6D38 FOREIGN KEY (order_id) REFERENCES ozon_orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_EF53A0928D9F6D38 ON ozon_order_status_history (order_id)');
        $this->addSql('ALTER TABLE ozon_orders ALTER status_updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER ozon_created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER ozon_updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN ozon_orders.status_updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ozon_orders.ozon_created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ozon_orders.ozon_updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ozon_orders.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ozon_orders.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE ozon_orders ADD CONSTRAINT FK_8E0BFFAC979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_8E0BFFAC979B1AD6 ON ozon_orders (company_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_company_scheme_ozon_updated_at ON ozon_orders (company_id, scheme, ozon_updated_at)');
        $this->addSql('ALTER INDEX idx_ozon_product_sales_product RENAME TO IDX_8CE737854584665A');
        $this->addSql('ALTER INDEX idx_ozon_product_sales_company RENAME TO IDX_8CE73785979B1AD6');
        $this->addSql('ALTER INDEX uniq_ozon_product_sales_period RENAME TO uniq_sales_period');
        $this->addSql('ALTER INDEX idx_ozon_product_stock_product RENAME TO IDX_BA730C644584665A');
        $this->addSql('ALTER INDEX idx_ozon_product_stock_company RENAME TO IDX_BA730C64979B1AD6');
        $this->addSql('ALTER TABLE ozon_sync_cursor ALTER last_since TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_sync_cursor ALTER last_to TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_sync_cursor ALTER last_run_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN ozon_sync_cursor.last_since IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ozon_sync_cursor.last_to IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ozon_sync_cursor.last_run_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE ozon_sync_cursor ADD CONSTRAINT FK_5C891BA3979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5C891BA3979B1AD6 ON ozon_sync_cursor (company_id)');
        $this->addSql('ALTER TABLE payment_plan ALTER planned_at TYPE DATE');
        $this->addSql('ALTER TABLE payment_plan ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE payment_plan ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN payment_plan.planned_at IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment_plan.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment_plan.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE payment_plan_match ALTER matched_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN payment_plan_match.matched_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE payment_recurrence_rule ALTER until TYPE DATE');
        $this->addSql('COMMENT ON COLUMN payment_recurrence_rule.until IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE pl_categories DROP CONSTRAINT fk_pl_category_parent');
        $this->addSql('DROP INDEX idx_plcat_company_parent_sort');
        $this->addSql('DROP INDEX uniq_plcat_company_code');
        $this->addSql('ALTER TABLE pl_categories ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pl_categories ALTER format TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pl_categories ALTER flow TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pl_categories ADD CONSTRAINT FK_AAE71C73727ACA70 FOREIGN KEY (parent_id) REFERENCES pl_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_pl_category_company RENAME TO IDX_AAE71C73979B1AD6');
        $this->addSql('ALTER INDEX idx_pl_category_parent RENAME TO IDX_AAE71C73727ACA70');
        $this->addSql('DROP INDEX idx_pl_daily_company_cat_date');
        $this->addSql('ALTER TABLE pl_daily_totals ALTER date TYPE DATE');
        $this->addSql('ALTER TABLE pl_daily_totals ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pl_daily_totals ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN pl_daily_totals.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN pl_daily_totals.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN pl_daily_totals.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE pl_daily_totals ADD CONSTRAINT FK_34A948D1979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pl_daily_totals ADD CONSTRAINT FK_34A948D198B34054 FOREIGN KEY (pl_category_id) REFERENCES pl_categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_34A948D1979B1AD6 ON pl_daily_totals (company_id)');
        $this->addSql('CREATE INDEX IDX_34A948D198B34054 ON pl_daily_totals (pl_category_id)');
        $this->addSql('ALTER TABLE pl_monthly_snapshots ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN pl_monthly_snapshots.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE pl_monthly_snapshots ADD CONSTRAINT FK_BC3D760D979B1AD6 FOREIGN KEY (company_id) REFERENCES "companies" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pl_monthly_snapshots ADD CONSTRAINT FK_BC3D760D98B34054 FOREIGN KEY (pl_category_id) REFERENCES pl_categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_BC3D760D979B1AD6 ON pl_monthly_snapshots (company_id)');
        $this->addSql('CREATE INDEX IDX_BC3D760D98B34054 ON pl_monthly_snapshots (pl_category_id)');
        $this->addSql('ALTER INDEX idx_project_directions_company RENAME TO IDX_51FE1CDE979B1AD6');
        $this->addSql('ALTER TABLE report_api_key ALTER scopes DROP DEFAULT');
        $this->addSql('ALTER TABLE report_api_key ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE report_api_key ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE report_api_key ALTER last_used_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE report_api_key ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN report_api_key.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN report_api_key.last_used_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN report_api_key.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_report_api_key_prefix_active ON report_api_key (key_prefix, is_active)');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_wb_sales_company RENAME TO IDX_94D5889E979B1AD6');
        $this->addSql('ALTER INDEX uniq_wb_sales_company_srid RENAME TO uniq_wb_sale_company_srid');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE auto_category_template (id UUID NOT NULL, company_id UUID NOT NULL, target_category_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, direction VARCHAR(255) NOT NULL, priority INT NOT NULL, stop_on_match BOOLEAN NOT NULL, match_logic VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scope VARCHAR(255) DEFAULT \'cashflow\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ac_template_category ON auto_category_template (target_category_id)');
        $this->addSql('CREATE INDEX idx_ac_template_company ON auto_category_template (company_id)');
        $this->addSql('CREATE INDEX idx_ac_template_company_scope_active ON auto_category_template (company_id, scope, is_active)');
        $this->addSql('CREATE INDEX idx_ac_template_priority ON auto_category_template (priority)');
        $this->addSql('CREATE TABLE auto_category_condition (id UUID NOT NULL, template_id UUID NOT NULL, field VARCHAR(255) NOT NULL, operator VARCHAR(255) NOT NULL, value TEXT NOT NULL, case_sensitive BOOLEAN NOT NULL, negate BOOLEAN NOT NULL, "position" INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ac_condition_template ON auto_category_condition (template_id)');
        $this->addSql('CREATE INDEX idx_ac_condition_template_position ON auto_category_condition (template_id, "position")');
        $this->addSql('ALTER TABLE auto_category_template ADD CONSTRAINT fk_ac_template_category FOREIGN KEY (target_category_id) REFERENCES cashflow_categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auto_category_template ADD CONSTRAINT fk_ac_template_company FOREIGN KEY (company_id) REFERENCES companies (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auto_category_condition ADD CONSTRAINT fk_ac_condition_template FOREIGN KEY (template_id) REFERENCES auto_category_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wildberries_report_details DROP CONSTRAINT FK_8C46D4BA979B1AD6');
        $this->addSql('DROP TABLE wildberries_report_details');
        $this->addSql('ALTER TABLE "counterparty" ALTER type TYPE VARCHAR(32)');
        $this->addSql('ALTER TABLE "counterparty" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "counterparty".created_at IS NULL');
        $this->addSql('CREATE INDEX idx_counterparty_company_name ON "counterparty" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_counterparty_company_inn ON "counterparty" (company_id, inn) WHERE (inn IS NOT NULL)');
        $this->addSql('ALTER TABLE "money_fund_movement" ALTER occurred_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "money_fund_movement".occurred_at IS NULL');
        $this->addSql('ALTER TABLE import_log ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE import_log ALTER finished_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE import_log ALTER created_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE import_log ALTER skipped_duplicates SET DEFAULT 0');
        $this->addSql('ALTER TABLE import_log ALTER errors_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE import_log ALTER preview SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN import_log.started_at IS NULL');
        $this->addSql('COMMENT ON COLUMN import_log.finished_at IS NULL');
        $this->addSql('ALTER TABLE "cashflow_categories" DROP CONSTRAINT FK_EAB5C38D727ACA70');
        $this->addSql('ALTER TABLE "cashflow_categories" ALTER operation_type TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE "cashflow_categories" ADD CONSTRAINT fk_cfc_parent FOREIGN KEY (parent_id) REFERENCES cashflow_categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_eab5c38d979b1ad6 RENAME TO idx_cfc_company');
        $this->addSql('ALTER INDEX idx_eab5c38d727aca70 RENAME TO idx_cfc_parent');
        $this->addSql('ALTER TABLE pl_categories DROP CONSTRAINT FK_AAE71C73727ACA70');
        $this->addSql('ALTER TABLE pl_categories ALTER type TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE pl_categories ALTER format TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE pl_categories ALTER flow TYPE VARCHAR(16)');
        $this->addSql('ALTER TABLE pl_categories ADD CONSTRAINT fk_pl_category_parent FOREIGN KEY (parent_id) REFERENCES pl_categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_plcat_company_parent_sort ON pl_categories (company_id, parent_id, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX uniq_plcat_company_code ON pl_categories (company_id, code)');
        $this->addSql('ALTER INDEX idx_aae71c73979b1ad6 RENAME TO idx_pl_category_company');
        $this->addSql('ALTER INDEX idx_aae71c73727aca70 RENAME TO idx_pl_category_parent');
        $this->addSql('ALTER TABLE "money_account" ALTER currency TYPE CHAR(3)');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS NULL');
        $this->addSql('ALTER TABLE cash_transaction DROP CONSTRAINT FK_925602C6979B1AD6');
        $this->addSql('ALTER TABLE cash_transaction DROP CONSTRAINT FK_925602C6B4D8145A');
        $this->addSql('ALTER TABLE cash_transaction DROP CONSTRAINT FK_925602C6DB1FAD05');
        $this->addSql('ALTER TABLE cash_transaction DROP CONSTRAINT FK_925602C6C2F6CD90');
        $this->addSql('DROP INDEX IDX_925602C6979B1AD6');
        $this->addSql('DROP INDEX IDX_925602C6B4D8145A');
        $this->addSql('DROP INDEX IDX_925602C6DB1FAD05');
        $this->addSql('DROP INDEX IDX_925602C6C2F6CD90');
        $this->addSql('ALTER TABLE cash_transaction ALTER occurred_at TYPE DATE');
        $this->addSql('ALTER TABLE cash_transaction ALTER booked_at TYPE DATE');
        $this->addSql('ALTER TABLE cash_transaction ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cash_transaction.occurred_at IS NULL');
        $this->addSql('COMMENT ON COLUMN cash_transaction.booked_at IS NULL');
        $this->addSql('COMMENT ON COLUMN cash_transaction.created_at IS NULL');
        $this->addSql('ALTER INDEX idx_925602c685d43df4 RENAME TO idx_ct_project_direction');
        $this->addSql('DROP INDEX idx_report_api_key_prefix_active');
        $this->addSql('ALTER TABLE "report_api_key" ALTER scopes SET DEFAULT \'reports:read\'');
        $this->addSql('ALTER TABLE "report_api_key" ALTER is_active SET DEFAULT true');
        $this->addSql('ALTER TABLE "report_api_key" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "report_api_key" ALTER last_used_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "report_api_key" ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "report_api_key".created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "report_api_key".last_used_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "report_api_key".expires_at IS NULL');
        $this->addSql('ALTER TABLE pl_monthly_snapshots DROP CONSTRAINT FK_BC3D760D979B1AD6');
        $this->addSql('ALTER TABLE pl_monthly_snapshots DROP CONSTRAINT FK_BC3D760D98B34054');
        $this->addSql('DROP INDEX IDX_BC3D760D979B1AD6');
        $this->addSql('DROP INDEX IDX_BC3D760D98B34054');
        $this->addSql('ALTER TABLE pl_monthly_snapshots ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN pl_monthly_snapshots.updated_at IS NULL');
        $this->addSql('ALTER INDEX idx_51fe1cde979b1ad6 RENAME TO idx_project_directions_company');
        $this->addSql('ALTER TABLE "companies" ALTER finance_lock_before TYPE DATE');
        $this->addSql('COMMENT ON COLUMN "companies".finance_lock_before IS NULL');
        $this->addSql('ALTER TABLE payment_plan ALTER planned_at TYPE DATE');
        $this->addSql('ALTER TABLE payment_plan ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE payment_plan ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN payment_plan.planned_at IS NULL');
        $this->addSql('COMMENT ON COLUMN payment_plan.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN payment_plan.updated_at IS NULL');
        $this->addSql('ALTER INDEX idx_94d5889e979b1ad6 RENAME TO idx_wb_sales_company');
        $this->addSql('ALTER INDEX uniq_wb_sale_company_srid RENAME TO uniq_wb_sales_company_srid');
        $this->addSql('ALTER TABLE payment_recurrence_rule ALTER until TYPE DATE');
        $this->addSql('COMMENT ON COLUMN payment_recurrence_rule.until IS NULL');
        $this->addSql('ALTER INDEX idx_882e16e985d43df4 RENAME TO idx_ctar_project_direction');
        $this->addSql('ALTER TABLE ozon_sync_cursor DROP CONSTRAINT FK_5C891BA3979B1AD6');
        $this->addSql('DROP INDEX IDX_5C891BA3979B1AD6');
        $this->addSql('ALTER TABLE ozon_sync_cursor ALTER last_since TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_sync_cursor ALTER last_to TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_sync_cursor ALTER last_run_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN ozon_sync_cursor.last_since IS NULL');
        $this->addSql('COMMENT ON COLUMN ozon_sync_cursor.last_to IS NULL');
        $this->addSql('COMMENT ON COLUMN ozon_sync_cursor.last_run_at IS NULL');
        $this->addSql('ALTER TABLE ozon_order_status_history DROP CONSTRAINT FK_EF53A0928D9F6D38');
        $this->addSql('DROP INDEX IDX_EF53A0928D9F6D38');
        $this->addSql('ALTER TABLE ozon_order_status_history ALTER changed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN ozon_order_status_history.changed_at IS NULL');
        $this->addSql('ALTER TABLE ozon_order_items DROP CONSTRAINT FK_53F702428D9F6D38');
        $this->addSql('ALTER TABLE ozon_order_items DROP CONSTRAINT FK_53F702424584665A');
        $this->addSql('DROP INDEX IDX_53F702428D9F6D38');
        $this->addSql('ALTER TABLE "money_fund" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "money_fund".created_at IS NULL');
        $this->addSql('ALTER INDEX idx_ba730c64979b1ad6 RENAME TO idx_ozon_product_stock_company');
        $this->addSql('ALTER INDEX idx_ba730c644584665a RENAME TO idx_ozon_product_stock_product');
        $this->addSql('ALTER TABLE pl_daily_totals DROP CONSTRAINT FK_34A948D1979B1AD6');
        $this->addSql('ALTER TABLE pl_daily_totals DROP CONSTRAINT FK_34A948D198B34054');
        $this->addSql('DROP INDEX IDX_34A948D1979B1AD6');
        $this->addSql('DROP INDEX IDX_34A948D198B34054');
        $this->addSql('ALTER TABLE pl_daily_totals ALTER date TYPE DATE');
        $this->addSql('ALTER TABLE pl_daily_totals ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pl_daily_totals ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN pl_daily_totals.date IS NULL');
        $this->addSql('COMMENT ON COLUMN pl_daily_totals.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN pl_daily_totals.updated_at IS NULL');
        $this->addSql('CREATE INDEX idx_pl_daily_company_cat_date ON pl_daily_totals (company_id, pl_category_id, date)');
        $this->addSql('ALTER TABLE ozon_orders DROP CONSTRAINT FK_8E0BFFAC979B1AD6');
        $this->addSql('DROP INDEX IDX_8E0BFFAC979B1AD6');
        $this->addSql('DROP INDEX idx_company_scheme_ozon_updated_at');
        $this->addSql('ALTER TABLE ozon_orders ALTER status_updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER ozon_created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER ozon_updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ozon_orders ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN ozon_orders.status_updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN ozon_orders.ozon_created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN ozon_orders.ozon_updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN ozon_orders.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN ozon_orders.updated_at IS NULL');
        $this->addSql('ALTER TABLE document_operations DROP CONSTRAINT FK_89D7F81EC33F7837');
        $this->addSql('ALTER TABLE document_operations ADD CONSTRAINT fk_doc_oper_document FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_89d7f81e12469de2 RENAME TO idx_doc_oper_category');
        $this->addSql('ALTER INDEX idx_89d7f81edb1fad05 RENAME TO idx_doc_oper_counterparty');
        $this->addSql('ALTER INDEX idx_89d7f81ec33f7837 RENAME TO idx_doc_oper_document');
        $this->addSql('ALTER TABLE documents ALTER date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN documents.date IS NULL');
        $this->addSql('CREATE INDEX idx_documents_company_type_date ON documents (company_id, type, date)');
        $this->addSql('ALTER INDEX idx_a2b07288979b1ad6 RENAME TO idx_document_company');
        $this->addSql('ALTER INDEX idx_a2b07288db1fad05 RENAME TO idx_document_counterparty');
        $this->addSql('ALTER INDEX idx_8ce73785979b1ad6 RENAME TO idx_ozon_product_sales_company');
        $this->addSql('ALTER INDEX idx_8ce737854584665a RENAME TO idx_ozon_product_sales_product');
        $this->addSql('ALTER INDEX uniq_sales_period RENAME TO uniq_ozon_product_sales_period');
        $this->addSql('ALTER TABLE payment_plan_match ALTER matched_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN payment_plan_match.matched_at IS NULL');
        $this->addSql('ALTER TABLE money_account_daily_balance DROP CONSTRAINT FK_FCE321EB979B1AD6');
        $this->addSql('ALTER TABLE money_account_daily_balance DROP CONSTRAINT FK_FCE321EBB4D8145A');
        $this->addSql('DROP INDEX IDX_FCE321EB979B1AD6');
        $this->addSql('DROP INDEX IDX_FCE321EBB4D8145A');
        $this->addSql('ALTER TABLE money_account_daily_balance ALTER date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN money_account_daily_balance.date IS NULL');
    }
}
