monolog:
    channels:
        - deprecation
        - import.bank1c
        - recalc
        - marketplace_ads

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug # В локальный файл пишем подробно
                channels: ["!event", "!doctrine", "!marketplace_ads"]

            marketplace_ads:
                type: rotating_file
                path: "%kernel.logs_dir%/marketplace_ads.log"
                level: debug
                channels: [marketplace_ads]
                max_files: 14

            sentry:
                type: service
                id: Sentry\Monolog\Handler
                level: error # В GlitchTip только ошибки
                channels: ["!marketplace_ads"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!marketplace_ads"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!marketplace_ads"]

            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json

            marketplace_ads:
                type: rotating_file
                path: "%kernel.logs_dir%/marketplace_ads.log"
                level: debug
                channels: [marketplace_ads]
                max_files: 14
                formatter: monolog.formatter.json

            sentry:
                type: service
                id: Sentry\Monolog\Handler
                level: error # В GlitchTip только ошибки
                channels: ["!marketplace_ads"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!marketplace_ads"]

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
