server {
    listen 80;
    charset utf-8;
    server_tokens off;

    resolver 127.0.0.11 ipv6=off valid=30s;

    access_log /var/log/nginx/tg-gateway.access.log;
    error_log /var/log/nginx/tg-gateway.error.log;

    client_max_body_size 5m;

    location /health {
        add_header Content-Type text/plain;
        return 200 'alive';
    }

    location = /telegram/webhook {
        set $app_upstream https://app.vashfindir.ru;

        proxy_pass $app_upstream/telegram/webhook;

        proxy_ssl_server_name on;
        proxy_ssl_name app.vashfindir.ru;

        proxy_set_header Host app.vashfindir.ru;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_connect_timeout 10s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;

        proxy_buffering off;
    }

    location / {
        return 404;
    }
}